
import { GoogleGenAI } from "@google/genai";

const getAIClient = () => {
  if (!process.env.API_KEY) {
    throw new Error("API Key is missing. Please ensure process.env.API_KEY is configured.");
  }
  return new GoogleGenAI({ apiKey: process.env.API_KEY });
};

export const generateMarketingBanner = async (
  logoBase64: string | null,
  customInstructions: string = ""
): Promise<string> => {
  const ai = getAIClient();
  const modelName = 'gemini-2.5-flash-image';

  // Base prompt focused on the requirements
  const basePrompt = `Create a professional, high-end commercial marketing banner for 'SoftApp Technologies', a leading Cyber Security training institute. 
  
  CORE REQUIREMENTS:
  1. Main Title: SoftApp Technologies
  2. Niche: Cyber Security Institute
  3. Key Selling Point: Include a prominent '100% Job Guarantee' badge or bold text.
  4. Tools to Feature (with labels): Wireshark, Metasploit, Nmap, Kali Linux, Burp Suite. Show these as professional technical icons or interface screenshots in a clean layout.
  
  VISUAL STYLE:
  - Futuristic, corporate, and secure aesthetic.
  - Background: Cyber-tech matrix, glowing network nodes, digital fingerprints, and firewall visualization.
  - Color Palette: Deep navy blue, neon cyan, and professional white.
  - Layout: Clean, modern, asymmetrical balance, high-quality typography.
  - Integrate the provided logo seamlessly into the top corner or center.

  ${customInstructions ? `USER ADDITIONS: ${customInstructions}` : ""}`;

  const parts: any[] = [{ text: basePrompt }];

  if (logoBase64) {
    // Extract actual base64 data if it includes data:image/... prefix
    const cleanBase64 = logoBase64.includes(',') ? logoBase64.split(',')[1] : logoBase64;
    parts.push({
      inlineData: {
        data: cleanBase64,
        mimeType: 'image/png'
      }
    });
  }

  try {
    const response = await ai.models.generateContent({
      model: modelName,
      contents: { parts },
      config: {
        imageConfig: {
          aspectRatio: "16:9",
        }
      }
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image was generated by the model.");
  } catch (error: any) {
    console.error("Gemini API Error:", error);
    throw new Error(error.message || "An unexpected error occurred during image generation.");
  }
};
